version: 2.1
jobs:
  build:
    docker:
      - image: node:14 # dapat diganti dengan versi Node.js yang Anda inginkan

    steps:
      - checkout

      # Langkah 1: Instal hadolint
      - run:
          name: Install hadolint
          command: |
            apt-get update && apt-get install -y hadolint

      # Langkah 2: Lint Dockerfile
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

      # Langkah 3: Build dan push Docker image
      - run:
          name: Build and Push Docker Image
          command: |
            # Build Docker image
            docker build -t muhammadardiyansyah/karsajobs-ui:latest .
            
            # mengubah nama image agar sesuai dengan format Github Packages
	    docker tag muhammadardiyansyah/karsajobs-ui:latest ghcr.io/muhammadardiyansyah/a433-microservices/karsajobs-ui:latest

            # Log in to Github Packages
            export CR_PAT=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
	    echo $CR_PAT | docker login ghcr.io -u muhammadardiyansyah --password-stdin

            # Push Docker image
            docker push ghcr.io/muhammadardiyansyah/a433-microservices/karsajobs-ui:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

